export const GLOBAL_SEARCH_FEATURE_ENABLED = true

export const GLOBAL_SEARCH_MIN_QUERY_LENGTH = 3
export const GLOBAL_SEARCH_DEBOUNCE_MS = 300
export const GLOBAL_SEARCH_TOP_RESULTS_PER_SECTION = 10

export const GLOBAL_SEARCH_DESKTOP_ONLY = true

export const GLOBAL_SEARCH_SHORTCUT = 'Mod+K'
